mongos:
  build: mongos 
  environment:
    MONGODB_SHARD: mongodb
    NODE_ID: 0
  links:
    - configdb
    - mongodb 
mongodb:
  build: mongodb 
  hostname: mongodb
  extra_hosts:
    - "mongodb:127.0.0.1"
  environment:
    NODE_ID: 0
    CLUSTER_SIZE: 1
    NODE_LIST: mongodb
  links:
    - configdb
configdb:
  build: mongodb 
  hostname: configdb 
  extra_hosts:
    - "configdb:127.0.0.1"
  environment:
    NODE_ID: 0
    NODE_LIST: configdb 
