version: "2"
services:
  mongos:
    image: washpost/mongos:authentication
    command: --configdb="${INSTANCE_IP}:27019"
    restart: always
    extra_hosts:
    {%- for node in aws.nodes %}
      - "node{{node.id}}:{{node.ip}}" 
    {%- endfor %}
    {%- if logging is defined and logging.driver is defined and logging.driver == "awslogs" %}
    logging: 
      driver: awslogs
      options:
        awslogs-group: {{ logging.meta.group }}
        awslogs-stream: mongos-node-${NODE_ID}
    {%- endif %}
    environment:
      MONGODB_SHARD: node0 
      MONGODB_HOST: ${INSTANCE_IP}
      CONFIGDB_HOST: ${INSTANCE_IP}
      NODE_ID: ${NODE_ID}
    {%- if MONGODB_ADMIN_PASSWORD is defined %}
      MONGODB_ADMIN_PASSWORD: {{ MONGODB_ADMIN_PASSWORD }}
    {%- endif %}
  mongodb:
    image: washpost/mongodb:authentication
    extra_hosts:
    {%- for node in aws.nodes %}
      - "node{{node.id}}:{{node.ip}}" 
    {%- endfor %}
    volumes:
      - "/data/mongodb/mongodb:/data/db"
    restart: always
    {%- if logging is defined and logging.driver is defined and logging.driver == "awslogs" %}
    logging: 
      driver: awslogs
      options:
        awslogs-group: {{ logging.meta.group }}
        awslogs-stream: mongodb-node-${NODE_ID}
    {%- endif %}
    environment:
      NODE_ID: ${NODE_ID} 
      NODE_LIST: node0,node1,node2
    {%- if MONGODB_ADMIN_PASSWORD is defined %}
      MONGODB_ADMIN_PASSWORD: {{ MONGODB_ADMIN_PASSWORD }}
    {%- endif %}
  configdb:
    image: washpost/mongodb:authentication
    restart: always
    extra_hosts:
    {%- for node in aws.nodes %}
      - "node{{node.id}}:{{node.ip}}" 
    {%- endfor %}
    {%- if logging is defined and logging.driver is defined and logging.driver == "awslogs" %}
    logging: 
      driver: awslogs
      options:
        awslogs-group: {{ logging.meta.group }}
        awslogs-stream: configdb-node-${NODE_ID}
    {%- endif %}
    environment:
      NODE_ID: ${NODE_ID} 
      NODE_LIST: node0,node1,node2
    {%- if MONGODB_ADMIN_PASSWORD is defined %}
      MONGODB_ADMIN_PASSWORD: {{ MONGODB_ADMIN_PASSWORD }}
    {%- endif %}
  snapshots:
    image: washpost/mongodb-snapshots:authentication
    restart: always
    {%- if logging is defined and logging.driver is defined and logging.driver == "awslogs" %}
    logging: 
      driver: awslogs
      options:
        awslogs-group: {{ logging.meta.group }}
        awslogs-stream: snapshots-node-${NODE_ID}
    {%- endif %}
    environment:
      CLUSTER_NAME: ${CLUSTER_NAME}
    {%- if MONGODB_ADMIN_PASSWORD is defined %}
      MONGODB_ADMIN_PASSWORD: {{ MONGODB_ADMIN_PASSWORD }}
    {%- endif %}
